stages:
  - build

pdf:
  stage: build
  script:
    - sed -i 's/archive.ubuntu.com/mirrors.tencentyun.com/g' /etc/apt/sources.list
    - bash ./build.sh
  artifacts:
    paths:
      - guide-book/guide-book.pdf
